name: Check and post to Bluesky
on:
  schedule:
    - cron: "55 10 * * *"
  workflow_dispatch:
jobs:
  post-job:
    name: Main Job
    runs-on: ubuntu-latest
    env:
      ATPROTO_HANDLE: ${{ secrets.ATPROTO_HANDLE }}
      ATPROTO_PASSWORD: ${{ secrets.ATPROTO_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: python gnd_gender.py

  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
