name: Check and post to Bluesky
on:
  schedule:
    - cron: "20 * * * *"
  workflow_dispatch: # Allow manual trigger

env:
  TZ: "Europe/Berlin"
  HOT_HOUR: "11"

jobs:
  post-job:
    name: Main Job
    runs-on: ubuntu-latest
    env:
      ATPROTO_HANDLE: ${{ secrets.ATPROTO_HANDLE }}
      ATPROTO_PASSWORD: ${{ secrets.ATPROTO_PASSWORD }}
    permissions:
      actions: write # Required to disable the workflow
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v30
      - uses: nix-community/cache-nix-action@v6
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ runner.os }}-
          # collect garbage until Nix store size (in bytes) is at most this number before trying to save a new cache
          # 1 GB = 1073741824 B
          gc-max-store-size-linux: 1073741824
          # do purge caches
          purge: true
          # purge all versions of the cache
          purge-prefixes: nix-${{ runner.os }}-
          # created more than this number of seconds ago relative to the start of the `Post Restore` phase
          purge-created: 0
          # except the version with the `primary-key`, if it exists
          purge-primary-key: never

      - run: nix build .
      - name: Run script
        id: run-script
        run: |
          trap 'echo "exitCode=$?" | tee -a $GITHUB_OUTPUT' EXIT
          if [ "$(date +%H)" = $HOT_HOUR ]; then
            # Post any outcome once a day
            ./result/bin/gnd-gender --post any
          else
            # Post positive outcome only at all other times
            ./result/bin/gnd-gender --post positive
          fi
      - name: Disable workflow on exit code 99 (changes detected)
        if: steps.run-script.outputs.exitCode == '99'
        run: gh workflow disable "$GITHUB_WORKFLOW"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
