name: Check and post to Bluesky
on:
  schedule:
    - cron: "20 * * * *"
  workflow_dispatch: # Allow manual trigger

env:
  TZ: "Europe/Berlin"
  HOT_HOUR: "11"

jobs:
  post-job:
    name: Main Job
    runs-on: ubuntu-latest
    env:
      ATPROTO_HANDLE: ${{ secrets.ATPROTO_HANDLE }}
      ATPROTO_PASSWORD: ${{ secrets.ATPROTO_PASSWORD }}
    permissions:
      actions: write # Required to disable the workflow
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        id: run-script
        run: |
          trap 'echo "exitCode=$?" | tee -a $GITHUB_OUTPUT' EXIT
          if [ "$(date +%H)" = $HOT_HOUR ]; then
            # Post any outcome once a day
            python gnd_gender.py --post any
          else
            # Post positive outcome only at all other times
            python gnd_gender.py --post positive
          fi
      - name: Disable workflow on exit code 99 (changes detected)
        if: steps.run-script.outputs.exitCode == '99'
        run: gh workflow disable "$GITHUB_WORKFLOW"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
